In [1]:
import numpy as np

In [6]:
def native_python_example():
    total = 0
    for x in range(1, 1_000_000):
        total += x
    return total

In [7]:
%timeit native_python_example()

65.9 ms ± 1.69 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [8]:
def numpy_example():
    return np.arange(1, 1_000_000).sum()

In [9]:
%timeit numpy_example()

1.6 ms ± 18.1 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [11]:
x = list(range(1, 1000))
y = [n + 1 for n in x] 

In [13]:
x = np.array(range(1, 1000))

In [14]:
x = np.arange(-1000, 1000)

In [15]:
x

array([-1000,  -999,  -998, ...,   997,   998,   999])

In [16]:
mask = x > 950

In [19]:
mask

array([False, False, False, ...,  True,  True,  True])

In [20]:
x[mask] 

array([951, 952, 953, 954, 955, 956, 957, 958, 959, 960, 961, 962, 963,
       964, 965, 966, 967, 968, 969, 970, 971, 972, 973, 974, 975, 976,
       977, 978, 979, 980, 981, 982, 983, 984, 985, 986, 987, 988, 989,
       990, 991, 992, 993, 994, 995, 996, 997, 998, 999])

In [21]:
# how many numbers match mask
mask.sum()

49

In [23]:
# sum all the numbers that match the mask
x[mask].sum()

47775

In [25]:
x[mask].mean()

975.0

In [29]:
x[mask].argmax()

48